regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'
  phone: !ruby/regexp '/\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/'

digits:
  length_name_max_50: 50
  length_email_max_255: 255
  length_password_min_6: 6
  length_phone_number: 10
  length_cmt_max: 255
  movie_per_page: 6
  admin_movie_per_page: 10
seat_code:
  seat_letter: ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
price:
  standard: 700000
  vip: 60000
seat_type:
  standard: 1
  vip: 2
ticket_status:
  available: 1
  choosen: 2
  unavailable: 3
payment_status:
  pending: 1
  approve: 2
  decline: 3
